
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BASE NUMBER\n    conversions : conversion\n                | conversions conversion\n    \n    conversion : NUMBER BASE\n    '
    
_lr_action_items = {'NUMBER':([0,1,2,4,5,],[3,3,-1,-2,-3,]),'$end':([1,2,4,5,],[0,-1,-2,-3,]),'BASE':([3,],[5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'conversions':([0,],[1,]),'conversion':([0,1,],[2,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> conversions","S'",1,None,None,None),
  ('conversions -> conversion','conversions',1,'p_conversions','GUI.py',33),
  ('conversions -> conversions conversion','conversions',2,'p_conversions','GUI.py',34),
  ('conversion -> NUMBER BASE','conversion',2,'p_conversion','GUI.py',40),
]
